# Generated by Django 6.0.5 on 2026-05-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(max_length=50)),
            ],
        ),
    ]
