# Generated by Django 6.0.5 on 2026-05-14 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('nin', models.CharField(max_length=255)),
                ('vehicle_type', models.CharField(choices=[('truck', 'Truck'), ('boda_boda', 'Boda Boda'), ('taxis', 'Taxis'), ('coaster', 'Coaster'), ('personal_car', 'Personal Car')], max_length=255)),
                ('number_plate', models.CharField(max_length=255)),
                ('vehicle_model', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=50)),
                ('arrival_time', models.DateTimeField(auto_now_add=True)),
                ('parking_charge', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=255)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingapp.vehicle')),
            ],
        ),
    ]
